// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUS1MDL74oTvsJ6-qosOoJM62EUgpEn9k',
    appId: '1:436922457701:web:0fce84ae7742a55b2cf08c',
    messagingSenderId: '436922457701',
    projectId: 'chatapp-84b35',
    authDomain: 'chatapp-84b35.firebaseapp.com',
    storageBucket: 'chatapp-84b35.firebasestorage.app',
    measurementId: 'G-RBQLKD18EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT9eALLE4RdcANTF2_WjEG_ggShbdYhEc',
    appId: '1:436922457701:android:370256f10b2c1e352cf08c',
    messagingSenderId: '436922457701',
    projectId: 'chatapp-84b35',
    storageBucket: 'chatapp-84b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpj9Kf-prYK-ao_4RM8wm83fHMNljFNjk',
    appId: '1:436922457701:ios:7b84a153b5d9c3122cf08c',
    messagingSenderId: '436922457701',
    projectId: 'chatapp-84b35',
    storageBucket: 'chatapp-84b35.firebasestorage.app',
    iosBundleId: 'com.example.smartDailyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpj9Kf-prYK-ao_4RM8wm83fHMNljFNjk',
    appId: '1:436922457701:ios:7b84a153b5d9c3122cf08c',
    messagingSenderId: '436922457701',
    projectId: 'chatapp-84b35',
    storageBucket: 'chatapp-84b35.firebasestorage.app',
    iosBundleId: 'com.example.smartDailyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUS1MDL74oTvsJ6-qosOoJM62EUgpEn9k',
    appId: '1:436922457701:web:396169e2e48edab72cf08c',
    messagingSenderId: '436922457701',
    projectId: 'chatapp-84b35',
    authDomain: 'chatapp-84b35.firebaseapp.com',
    storageBucket: 'chatapp-84b35.firebasestorage.app',
    measurementId: 'G-6TPRTJVM8L',
  );
}
